"""Add event status type price

Revision ID: 50439dd282a3
Revises: a8f672f59893
Create Date: 2025-12-17 06:02:56.228791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50439dd282a3'
down_revision: Union[str, None] = 'a8f672f59893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('status', sa.String(), nullable=False, server_default='DRAFT'))
    op.add_column('event', sa.Column('event_type', sa.String(), nullable=False, server_default='MEETING'))
    op.add_column('event', sa.Column('ticket_price', sa.Float(), nullable=True))
    op.add_column('event', sa.Column('registration_deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'registration_deadline')
    op.drop_column('event', 'ticket_price')
    op.drop_column('event', 'event_type')
    op.drop_column('event', 'status')
    # ### end Alembic commands ###
