"""add_event_strategy_tables

Revision ID: 7057a8219a47
Revises: 50439dd282a3
Create Date: 2025-12-17 18:47:51.474350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7057a8219a47'
down_revision: Union[str, None] = '50439dd282a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emaillist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'FAILED', name='emailliststatus'), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emaillist_id'), 'emaillist', ['id'], unique=False)
    op.create_index(op.f('ix_emaillist_name'), 'emaillist', ['name'], unique=False)
    op.create_table('eventbudget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('planned_amount', sa.Float(), nullable=True),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.Column('forecast_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventbudget_id'), 'eventbudget', ['id'], unique=False)
    op.create_table('eventesg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventesg_id'), 'eventesg', ['id'], unique=False)
    op.create_table('eventgoal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventgoal_id'), 'eventgoal', ['id'], unique=False)
    op.add_column('event', sa.Column('region', sa.String(), nullable=True))
    op.add_column('event', sa.Column('is_template', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('parent_event_id', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('scenario_type', sa.String(), server_default='IN_PERSON', nullable=False))
    op.add_column('event', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'event', 'event', ['parent_event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'is_public')
    op.drop_column('event', 'scenario_type')
    op.drop_column('event', 'parent_event_id')
    op.drop_column('event', 'is_template')
    op.drop_column('event', 'region')
    op.drop_index(op.f('ix_eventgoal_id'), table_name='eventgoal')
    op.drop_table('eventgoal')
    op.drop_index(op.f('ix_eventesg_id'), table_name='eventesg')
    op.drop_table('eventesg')
    op.drop_index(op.f('ix_eventbudget_id'), table_name='eventbudget')
    op.drop_table('eventbudget')
    op.drop_index(op.f('ix_emaillist_name'), table_name='emaillist')
    op.drop_index(op.f('ix_emaillist_id'), table_name='emaillist')
    op.drop_table('emaillist')
    # ### end Alembic commands ###
