"""Add Position model and link to Election

Revision ID: 70e70d1d8cf6
Revises: 9a6d3fd9871a
Create Date: 2025-12-18 11:57:21.537910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e70d1d8cf6'
down_revision: Union[str, None] = '9a6d3fd9871a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('term_length', sa.String(), nullable=True),
    sa.Column('is_executive', sa.Boolean(), nullable=True),
    sa.Column('current_holder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_holder_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_id'), 'position', ['id'], unique=False)
    op.create_index(op.f('ix_position_title'), 'position', ['title'], unique=False)
    op.add_column('election', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'election', 'position', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'election', type_='foreignkey')
    op.drop_column('election', 'position_id')
    op.drop_index(op.f('ix_position_title'), table_name='position')
    op.drop_index(op.f('ix_position_id'), table_name='position')
    op.drop_table('position')
    # ### end Alembic commands ###
