"""Add member profile fields

Revision ID: 9a6d3fd9871a
Revises: 0ed42107af66
Create Date: 2025-12-18 11:29:46.604123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6d3fd9871a'
down_revision: Union[str, None] = '0ed42107af66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('user', sa.Column('linkedin_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'linkedin_url')
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
